/*
============================================================================================
Copyright     : Portage Now, 2025
Created By    : Pratul Dwivedi
Modified Date : 25-Sep-2026
Description   : Admin-managed website navigation: website_nav_items (a parent/child tree)
                and website_nav_item_translations, plus the website-documents bucket for
                the PDFs document items point at.

                Every item is one of three kinds:
                  link      navigates to href — an internal route (/about-us/) or an
                            external URL.
                  page      a CMS page rendered from body_html at the URL formed by its
                            ancestors' slugs (/reports-policies/annual-reports/). A page
                            also lists its published children below the body.
                  document  a PDF in the website-documents bucket (file_path). The menu
                            opens it, in a new tab when open_in_new_tab is set.

                show_in_menu decides whether an item appears in the header dropdown or
                only in its parent page's listing, so the tree can go deeper than the
                two levels the header renders (e.g. Annual Reports > 2024-25 > PDFs).

                website_nav_items holds the English content; a translation row overrides
                title, body_html and the PDF for one other locale, and each of those
                falls back to English when missing (see fn_get_website_nav).

                No RLS policies on purpose — same as website_blog_translations: RLS is
                enabled with nothing granted, so the only access path is the
                SECURITY DEFINER fn_*website_nav* functions.
============================================================================================
*/

CREATE TABLE public.website_nav_items (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       integer REFERENCES public.website_nav_items(id) ON DELETE CASCADE,
    -- URL segment, unique among active siblings. Language-neutral: /te/ URLs
    -- use the same slugs.
    slug            text    NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    kind            text    NOT NULL CHECK (kind IN ('link', 'page', 'document')),
    title           text    NOT NULL,
    href            text,
    body_html       text,
    -- Object path inside the website-documents bucket, and the original file
    -- name shown to visitors.
    file_path       text,
    file_name       text,
    open_in_new_tab boolean NOT NULL DEFAULT false,
    show_in_menu    boolean NOT NULL DEFAULT true,
    sort_order      integer NOT NULL DEFAULT 0,
    published       boolean NOT NULL DEFAULT true,
    data            jsonb   NOT NULL DEFAULT '{}'::jsonb,
    -- Read by fn_can_access_row, like every other website_* table.
    access_control  jsonb,
    tenant_id       integer NOT NULL REFERENCES public.tenants(id),
    is_active       boolean NOT NULL DEFAULT true,
    created_by      integer NOT NULL REFERENCES public.profiles(id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      integer REFERENCES public.profiles(id),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT website_nav_items_link_href_chk
        CHECK (kind <> 'link' OR length(trim(COALESCE(href, ''))) > 0),
    CONSTRAINT website_nav_items_document_file_chk
        CHECK (kind <> 'document' OR length(trim(COALESCE(file_path, ''))) > 0),
    CONSTRAINT website_nav_items_not_own_parent_chk
        CHECK (parent_id IS DISTINCT FROM id)
);

-- Sibling slugs must be unique, since they form the page URL. Soft-deleted
-- rows don't count, so a deleted item's slug can be reused.
CREATE UNIQUE INDEX website_nav_items_sibling_slug_key
    ON public.website_nav_items (tenant_id, COALESCE(parent_id, 0), slug)
    WHERE is_active;
CREATE INDEX website_nav_items_parent_idx ON public.website_nav_items (parent_id);

ALTER TABLE public.website_nav_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.website_nav_items FROM anon, authenticated;

CREATE TABLE public.website_nav_item_translations (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id     integer NOT NULL REFERENCES public.website_nav_items(id) ON DELETE CASCADE,
    -- ISO 639 language code. English lives on website_nav_items itself.
    locale      text    NOT NULL CHECK (locale ~ '^[a-z]{2,3}$' AND locale <> 'en'),
    title       text    NOT NULL,
    -- NULL = reuse the English body / PDF.
    body_html   text,
    file_path   text,
    file_name   text,
    published   boolean NOT NULL DEFAULT true,
    tenant_id   integer NOT NULL REFERENCES public.tenants(id),
    is_active   boolean NOT NULL DEFAULT true,
    created_by  integer NOT NULL REFERENCES public.profiles(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_by  integer REFERENCES public.profiles(id),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT website_nav_item_translations_item_locale_key UNIQUE (item_id, locale)
);

CREATE INDEX website_nav_item_translations_tenant_idx ON public.website_nav_item_translations (tenant_id);

ALTER TABLE public.website_nav_item_translations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.website_nav_item_translations FROM anon, authenticated;

-- ── website-documents bucket ─────────────────────────────────────────────
-- Public PDFs only. Admins upload straight from the browser (Vercel caps
-- function request bodies at 4.5 MB, well below a typical annual report),
-- so the 50 MB limit here is the real one.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('website-documents', 'website-documents', true, 52428800, ARRAY['application/pdf'])
ON CONFLICT (id) DO NOTHING;

-- Same pair of policies as website-media / blog-covers.
CREATE POLICY website_documents_public_read ON storage.objects
    FOR SELECT
    USING (bucket_id = 'website-documents');

CREATE POLICY website_documents_admin_write ON storage.objects
    FOR ALL
    USING (bucket_id = 'website-documents' AND fn_is_admin())
    WITH CHECK (bucket_id = 'website-documents' AND fn_is_admin());
