/*
============================================================================================
Copyright     : Portage Now, 2025
Created By    : Pratul Dwivedi
Modified Date : 25-Sep-2026
Description   : Per-locale translations of website_blogs rows.

                website_blogs stays the source of truth for everything language-neutral
                (slug, category, cover image, tags, author, dates) and for its English
                content. A row here overrides only the reader-facing text for one other
                locale; fn_get_website_blogs(p_locale := 'te') coalesces it over the
                English columns and falls back to English per post when no published
                translation exists.

                Purely additive: no existing table, column or function changes here.

                No RLS policies on purpose — RLS is enabled with nothing granted, so the
                only access path is through the SECURITY DEFINER fn_*_website_blog_translation
                functions and fn_get_website_blogs, which do their own tenant/access checks.
============================================================================================
*/

CREATE TABLE public.website_blog_translations (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id     integer NOT NULL REFERENCES public.website_blogs(id) ON DELETE CASCADE,
    -- ISO 639 language code. English lives on website_blogs itself.
    locale      text    NOT NULL CHECK (locale ~ '^[a-z]{2,3}$' AND locale <> 'en'),
    title       text    NOT NULL,
    excerpt     text    NOT NULL,
    -- NULL = reuse the English cover_alt.
    cover_alt   text,
    body        jsonb   NOT NULL,
    -- Same shape as website_blogs.data (e.g. { "faqs": [...] }).
    data        jsonb,
    published   boolean NOT NULL DEFAULT true,
    tenant_id   integer NOT NULL REFERENCES public.tenants(id),
    is_active   boolean NOT NULL DEFAULT true,
    created_by  integer NOT NULL REFERENCES public.profiles(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_by  integer REFERENCES public.profiles(id),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT website_blog_translations_blog_locale_key UNIQUE (blog_id, locale)
);

CREATE INDEX website_blog_translations_tenant_idx ON public.website_blog_translations (tenant_id);

ALTER TABLE public.website_blog_translations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.website_blog_translations FROM anon, authenticated;
