/*
============================================================================================
Copyright     : Portage Now, 2025
Created By    : Pratul Dwivedi
Modified Date : 28-Sep-2026
Description   : Resync every identity/serial sequence in the public schema with its
                table's current max(id).

                The data was copied into the new database with its original ids, which
                doesn't advance a GENERATED BY DEFAULT AS IDENTITY (or serial) sequence.
                Each sequence therefore restarted at 1 and every INSERT that relies on
                the default id collided with an existing row — e.g.
                fn_save_website_nav_item returning "A record with this value already
                exists" when creating a new navigation item.

                setval(seq, max(col)) makes the next id max+1; an empty table gets
                setval(seq, 1, false) so its next id is 1. Safe to re-run.
============================================================================================
*/

DO $$
DECLARE
    r        record;
    v_max    bigint;
BEGIN
    FOR r IN
        SELECT c.table_schema,
               c.table_name,
               c.column_name,
               pg_get_serial_sequence(format('%I.%I', c.table_schema, c.table_name), c.column_name) AS seq
        FROM   information_schema.columns c
        JOIN   information_schema.tables t
               ON t.table_schema = c.table_schema AND t.table_name = c.table_name
        WHERE  c.table_schema = 'public'
          AND  t.table_type   = 'BASE TABLE'
          AND  (c.is_identity = 'YES' OR c.column_default LIKE 'nextval(%')
    LOOP
        CONTINUE WHEN r.seq IS NULL;

        EXECUTE format('SELECT max(%I) FROM %I.%I', r.column_name, r.table_schema, r.table_name)
        INTO v_max;

        IF v_max IS NULL THEN
            PERFORM setval(r.seq, 1, false);
        ELSE
            PERFORM setval(r.seq, v_max, true);
        END IF;

        RAISE NOTICE '%.% (%): next id %', r.table_name, r.column_name, r.seq, COALESCE(v_max, 0) + 1;
    END LOOP;
END;
$$;
